#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os

debug_cxxflags = '''
-DV8_DEPRECATION_WARNINGS
-D_FILE_OFFSET_BITS=64
-DCHROMIUM_BUILD
-DUSE_CAIRO=1
-DUSE_GLIB=1
-DUSE_DEFAULT_RENDER_THEME=1
-DUSE_LIBJPEG_TURBO=1
-DUSE_NSS=1
-DUSE_X11=1
-DENABLE_ONE_CLICK_SIGNIN
-DGTK_DISABLE_SINGLE_INCLUDES=1
-DUSE_XI2_MT=2
-DENABLE_REMOTING=1
-DENABLE_WEBRTC=1
-DENABLE_PEPPER_CDMS
-DENABLE_CONFIGURATION_POLICY
-DENABLE_INPUT_SPEECH
-DENABLE_NOTIFICATIONS
-DUSE_UDEV
-DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC
-DENABLE_EGLIMAGE=1
-DENABLE_TASK_MANAGER=1
-DENABLE_EXTENSIONS=1
-DENABLE_PLUGIN_INSTALLATION=1
-DENABLE_PLUGINS=1
-DENABLE_SESSION_SERVICE=1
-DENABLE_THEMES=1
-DENABLE_BACKGROUND=1
-DENABLE_AUTOMATION=1
-DENABLE_GOOGLE_NOW=1
-DCLD_VERSION=2
-DENABLE_FULL_PRINTING=1
-DENABLE_PRINTING=1
-DENABLE_SPELLCHECK=1
-DENABLE_CAPTIVE_PORTAL_DETECTION=1
-DENABLE_MANAGED_USERS=1
-DENABLE_MDNS=1
-DUSING_CEF_SHARED
-D__STDC_CONSTANT_MACROS
-D__STDC_FORMAT_MACROS
-DDYNAMIC_ANNOTATIONS_ENABLED=1
-DWTF_USE_DYNAMIC_ANNOTATIONS=1
-D_DEBUG
-D_GLIBCXX_DEBUG=1
'''.split()

release_cxxflags = '''
-DANGLE_DX11
-D_FILE_OFFSET_BITS=64
-DCHROMIUM_BUILD
-DUSE_DEFAULT_RENDER_THEME=1
-DUSE_LIBJPEG_TURBO=1
-DUSE_NSS=1
-DUSE_X11=1
-DENABLE_ONE_CLICK_SIGNIN
-DGTK_DISABLE_SINGLE_INCLUDES=1
-DUSE_XI2_MT=2
-DENABLE_REMOTING=1
-DENABLE_WEBRTC=1
-DENABLE_PEPPER_CDMS
-DENABLE_CONFIGURATION_POLICY
-DENABLE_INPUT_SPEECH
-DENABLE_NOTIFICATIONS
-DENABLE_GPU=1
-DENABLE_EGLIMAGE=1
-DENABLE_TASK_MANAGER=1
-DENABLE_EXTENSIONS=1
-DENABLE_PLUGIN_INSTALLATION=1
-DENABLE_PLUGINS=1
-DENABLE_SESSION_SERVICE=1
-DENABLE_THEMES=1
-DENABLE_BACKGROUND=1
-DENABLE_AUTOMATION=1
-DENABLE_GOOGLE_NOW=1
-DCLD_VERSION=1
-DENABLE_FULL_PRINTING=1
-DENABLE_PRINTING=1
-DENABLE_SPELLCHECK=1
-DENABLE_CAPTIVE_PORTAL_DETECTION=1
-DENABLE_MANAGED_USERS=1
-DENABLE_MDNS=1
-DUSING_CEF_SHARED
-D__STDC_CONSTANT_MACROS
-D__STDC_FORMAT_MACROS
-DNVALGRIND
-DDYNAMIC_ANNOTATIONS_ENABLED=0
-D_FORTIFY_SOURCE=2
-DNDEBUG
'''.split()

def get_cxxflags (debug=False):
    if debug: return debug_cxxflags
    else: return release_cxxflags

def get_outdir (debug=False):
    if debug: return 'libs/cef_binary/out/Debug'
    else: return 'libs/cef_binary/out/Release'

def get_file (path, debug=False):
    return os.path.join (get_outdir (debug), path)
